// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDna1XfYnhsHTlu1zLnm4q2-1T3ncYMZ8Q',
    appId: '1:777938381037:web:486bfb76e7834fde82c4e4',
    messagingSenderId: '777938381037',
    projectId: 'flutter-authproject',
    authDomain: 'flutter-authproject.firebaseapp.com',
    storageBucket: 'flutter-authproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx592bEYszwtssqak8K4tFhuVkEGxmhk8',
    appId: '1:777938381037:android:9fcf04e036d5ba7782c4e4',
    messagingSenderId: '777938381037',
    projectId: 'flutter-authproject',
    storageBucket: 'flutter-authproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJYmOhaju6q-0P-5ZwgUJq_8PWBWO6Rc',
    appId: '1:777938381037:ios:2699a3af33944c1a82c4e4',
    messagingSenderId: '777938381037',
    projectId: 'flutter-authproject',
    storageBucket: 'flutter-authproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJYmOhaju6q-0P-5ZwgUJq_8PWBWO6Rc',
    appId: '1:777938381037:ios:2699a3af33944c1a82c4e4',
    messagingSenderId: '777938381037',
    projectId: 'flutter-authproject',
    storageBucket: 'flutter-authproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDna1XfYnhsHTlu1zLnm4q2-1T3ncYMZ8Q',
    appId: '1:777938381037:web:a8043204ddb9451382c4e4',
    messagingSenderId: '777938381037',
    projectId: 'flutter-authproject',
    authDomain: 'flutter-authproject.firebaseapp.com',
    storageBucket: 'flutter-authproject.firebasestorage.app',
  );

}